/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pratikum120625;

/**
 *
 * @author asus
 */
public class kreasi extends javax.swing.JFrame {
    private double suhuAwal;
    private String satuanAwal;
    /**
     * Creates new form kreasi
     */
    public kreasi() {
        initComponents();
        suhuAwal = 0;
        satuanAwal = "C";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnC = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnKonversi = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI KONVERSI SUHU");

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        btnC.setText("°C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnF.setText("°F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnK.setText("°K");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasil Konversi :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnK)
                                .addGap(4, 4, 4)
                                .addComponent(btnKonversi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC)
                    .addComponent(btnF)
                    .addComponent(btnK)
                    .addComponent(btnKonversi)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtInput.setText("0");
        txtHasil.setText("0");
        suhuAwal = 0;
        satuanAwal = "C";
        btnC.setBackground(new java.awt.Color(204, 204, 255));
        btnF.setBackground(new java.awt.Color(204, 255, 204));
        btnK.setBackground(new java.awt.Color(255, 204, 204));
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        satuanAwal = "C";
        btnC.setBackground(new java.awt.Color(153, 153, 255));
        btnF.setBackground(new java.awt.Color(204, 255, 204));
    }//GEN-LAST:event_btnCActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        satuanAwal = "F";
        btnC.setBackground(new java.awt.Color(204, 204, 255));
        btnF.setBackground(new java.awt.Color(153, 255, 153));
        btnK.setBackground(new java.awt.Color(255, 204, 204));
    }//GEN-LAST:event_btnFActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
       satuanAwal = "K";
        btnC.setBackground(new java.awt.Color(204, 204, 255));
        btnF.setBackground(new java.awt.Color(204, 255, 204));
        btnK.setBackground(new java.awt.Color(255, 153, 153));
    }//GEN-LAST:event_btnKActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        try {
            suhuAwal = Double.parseDouble(txtInput.getText());
            double hasil = 0;
            String satuanHasil = "";
            
            // Konversi ke semua satuan lainnya
            if (satuanAwal.equals("C")) {
                // C ke F
                double fahrenheit = (suhuAwal * 9/5) + 32;
                // C ke K
                double kelvin = suhuAwal + 273.15;
                
                hasil = (btnF.getBackground().equals(new java.awt.Color(153, 255, 153))) ? fahrenheit : kelvin;
                satuanHasil = (btnF.getBackground().equals(new java.awt.Color(153, 255, 153))) ? "°F" : "K";
            } 
            else if (satuanAwal.equals("F")) {
                // F ke C
                double celcius = (suhuAwal - 32) * 5/9;
                // F ke K
                double kelvin = (suhuAwal - 32) * 5/9 + 273.15;
                
                hasil = (btnC.getBackground().equals(new java.awt.Color(153, 153, 255))) ? celcius : kelvin;
                satuanHasil = (btnC.getBackground().equals(new java.awt.Color(153, 153, 255))) ? "°C" : "K";
            } 
            else if (satuanAwal.equals("K")) {
                // K ke C
                double celcius = suhuAwal - 273.15;
                // K ke F
                double fahrenheit = (suhuAwal - 273.15) * 9/5 + 32;
                
                hasil = (btnC.getBackground().equals(new java.awt.Color(153, 153, 255))) ? celcius : fahrenheit;
                satuanHasil = (btnC.getBackground().equals(new java.awt.Color(153, 153, 255))) ? "°C" : "°F";
            }
            
            // Tampilkan hasil
            txtHasil.setText(String.format("%.2f %s", hasil, satuanHasil));
            
        } catch (NumberFormatException e) {
            txtHasil.setText("Input tidak valid");
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kreasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kreasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kreasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kreasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kreasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
